const fs = require('fs')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


global.SESSION_ID = process.env.SESSION_ID || 'IMMU-MD:~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQUdXd3ZnZWIrN2MveEsyMnpEVnFJYzFzcWFIZFJUODFhS0VWa0twLytVdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0dFaWJGcnRvbXZWcUFPdGJ2djJZbmsxVVNFR0VndU8yNFR0NDg5S2tScz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLS0dZT3E0Y0VGbUZUUzFWa05ZcmpDQjJTSUpnTGdrMlVEU1lsNHVIakdjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJxM2hka3FZTU9RR3REMFpFZE5GdnlLdFY0Q2hBSkJSeUJvNkZJN1F1cVVZPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjRJS1VQQWRFeTRWY0RnbFFLTVBXSnY4MTRwdVB6UHFIV3lwMEdTQTVLRjA9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InQ2bjV5NjFvcGJXUXlxd1djZUI4cHpoSzB1L0JLbm4wQzVCSVdpQXU1QVE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUIwV2FtTDlKc3lPcXZYWkh2bFJHaFV6Z3A0TUl3cEFqa21lT0RXekEzST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkg2VXZuUm83clhJMHNoQWVJMUpVaEZ3aE9xRjJ4b0lkUExEeEFGSDZYST0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkhkUndNNE5UZms3SnZZaHJWU1NFL0srdWhmMDEwS3dya0ozdmsvSm9Sck0rSGZvVFJDK1dvSU5NOVRZTnk3c3JVelExNTk3dGJoR2FvcmFISDVHMGl3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6OTUsImFkdlNlY3JldEtleSI6IkhDK1cxNUg0aHhmK0toM3IrNStDMTdyczE0RTkyTFRCN25ZdjNhRjU1WGc9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTIzMTgyNTQxMzg4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkQyRjUyRUY4RTA0NEFBMTk1N0UyRUNCNTdDQkU1QjA3In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTA3OTc0ODl9LHsia2V5Ijp7InJlbW90ZUppZCI6IjkyMzE4MjU0MTM4OEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI1RTNGNTYyNEMyQ0M5MDY4QUQ3MjdEQUVDRDY5MzU0NyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUwNzk3NDkxfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJTSFJBWFdUNyIsIm1lIjp7ImlkIjoiOTIzMTgyNTQxMzg4OjE1QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IvCdkJLwnZCI8J2QhvCdkIzwnZCAIiwibGlkIjoiMTM5MzYzNjUyNTI2MjMyOjE1QGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUDJDd3lzUW5wbnN3Z1lZQWlBQUtBQT0iLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiYVdLRGpvWi9UcytDRkJNZ3A0VTlpb2ZiaGVZbEppbnMzR0x3cGFJejRtRT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiVHU4MGUwZjZzOXpXWERnZDN2QTQ5Q3AzQzRPN0Z5aVlpOTRUUTU2YzRGcndHVHRoYjhXQWZ0TFpQaVl5elgrNXJoZHh0eFNpYndhRW9DWXhBWE1pQ2c9PSIsImRldmljZVNpZ25hdHVyZSI6IkhEazk0eTd2ZGYzZEQ2all3Y1Z5emlUV2tRazZlUjhUQzVKS2E1WTdiNk1Gd1hIQnFmK1FQYks4UlJiSEh0QUVDMzA4T1lsblRrNStmK2Y0cHFkd2hBPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTIzMTgyNTQxMzg4OjE1QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQldsaWc0NkdmMDdQZ2hRVElLZUZQWXFIMjRYbUpTWXA3TnhpOEtXaU0rSmgifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBVUlEUT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc1MDc5NzQ4MiwibGFzdFByb3BIYXNoIjoiM1I5WjM5IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFMcXEifQ=='


global.PREFIX = process.env.PREFIXZ || '.'


global.mode = process.env.MODE || 'public';
// Set 'private' to enable private mode
// Set 'public' to enable public mode


global.botname = process.env.BOT_NAME || 'IMMU MD'

global.ownernumber = process.env.OWNER_NUMBER || '923182541388'


global.antidelete = process.env.ANTIDELETE || 'private'
// options:- 'private', 'chat' or 'off'
// private = Sends to message yourself 
// chat = sends to the current chat 
// off = Disables detection of deleted messages


global.statusemoji = process.env.STATUS_EMOJI || "🧡,💚,🔥,✨,❤️,🥰,😎";


global.autoviewstatus = process.env.AUTO_STATUS_VIEW || 'true'


global.autoreactstatus = process.env.AUTO_STATUS_REACT || 'false'


global.timezones = process.env.TIMEZONE || "Pakistan/Karachi" 

let file = require.resolve(__filename)
fs.watchFile(file, () => {
  fs.unwatchFile(file)
  console.log(`Updated '${__filename}'`)
  delete require.cache[file]
  require(file)
})
