const fs = require('fs')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


global.SESSION_ID = process.env.SESSION_ID |IMMU-MD:~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSU5BOTVOWHdyaEtXOUV1WTc4YmpIbWYwMnp2QS9abEI2dzJ3OUhTeGRuND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWk81bXNWRHR6cGtoYWdlcmJLMXpzQ0trZWR2b2JLb3l3N3lSRlFLS3dRUT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJrTWJnWjhJbGNUNlA4THE5K3owNkRQTzkva2lnRzJwZ0c4NXNjSlVDTGtRPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHRzJWb1NMenBIRDZBYmFNNjBiZXJ4VzdGbmkrNFBnYWptbFd6THA2dEFNPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IndFemR5RHdIM25EOXFXYnQ3WDlHZ0lvTFV3dzA3VU5zR0RGN01YSWJVRTg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlpGTXNWcmNEYzhPUGc5alN0U0FxY1JWQ1RyQ3ZkcWxjdFdqMVdpYytmWGs9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkF0R1VUTDM2RGNWS0I3c1A1Y2dQZCs2TUhqYkQrQ3RlWk9tWm9jWGJFcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWmJGalZyMHNEeitvVmlOOWNhYndtMlN6TjdPUFU5TEQvaTQxZk92NkNqVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZ0Zld4dUV4UEYyZittQ1FUK2dOUWd1MUNKSlFCemlhWk92WVFFbWorZUJMNjQwSnd6cVZjcndkR2R1L0JMWmZTeHNFQ0VZNWhXRHc0bW13Mzc1RkJnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjI0LCJhZHZTZWNyZXRLZXkiOiJYSDE3MDNXM2JFc0NwOWREQkgxSy9sZU1BWm1aSWNvanZ6ZDBWdnduV2I0PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjkyMzcwMTU5NDgwMUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIzMTgzQzZBRjE3RjcxN0IzMkU3NEE5RDI2Mzk3RDI3NiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUwNjQxODU0fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5MjM3MDE1OTQ4MDFAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiRDcxMEFCNTBDOEZGNDA0QjBDNzAwRTJCQjRGRDZERjEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1MDY0MTg1Nn1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiUE5YNEJQODMiLCJtZSI6eyJpZCI6IjkyMzcwMTU5NDgwMTo0NUBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiLwk4apy5rigKLwk4SC8J2Qism04bSP4bShybTwk4aZ4oCiy5rwk4aqICAgICAgICAgICAg44CGzY7wk4apy5DNouG0gOqcscuQzaLiuJnCs/CThqogICAgICAgICAgICAgICAgICAgICDwk4apIPCThILLmuKAovCdkIzhtIDKn8mq4bSL4oCiwrPwk4aqIiwibGlkIjoiMTg4OTgzNDc2NzQ4NDgxOjQ1QGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTURJOVN3UXJ0bml3Z1lZQVNBQUtBQT0iLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoieENRQWJXMnNyY3I4VTNnSm5QMXE3NlRSaFdrOW5VMnBCelZvcG04NkJocz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiMnMzdjM1U09nejMralFpVTF0WU82QzM3Y0VXWmI5LzlVT0N2KzZodVBpU2pKMmNjNlRVWkNBOGY5ZlBJZnIwZkxFaXRmY2Q4UWRicVlKWjdVekxDQ2c9PSIsImRldmljZVNpZ25hdHVyZSI6ImJYazBNVzdsNEJLUkFIZGVadFNxSDVEY3dNLzZOMDBtS2RxeG8ydExvSHNqK2V4QlhybWxPeHJvb2RraHdLT3RyUmVIMEpqTlZVS3J6VDhCek85Q0FnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTIzNzAxNTk0ODAxOjQ1QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmNRa0FHMXRySzNLL0ZONENaejlhdStrMFlWcFBaMU5xUWMxYUtadk9nWWIifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNCSUlDQT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc1MDY0MTg1MSwibGFzdFByb3BIYXNoIjoiMlY3N3FVIiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFBS0MifQ==| ''


global.PREFIX = process.env.PREFIXZ || '.'


global.mode = process.env.MODE || 'public';
// Set 'private' to enable private mode
// Set 'public' to enable public mode


global.botname = process.env.BOT_NAME || 'IMMU MD'

global.ownernumber = process.env.OWNER_NUMBER || '92xxxxxxxxx'


global.antidelete = process.env.ANTIDELETE || 'private'
// options:- 'private', 'chat' or 'off'
// private = Sends to message yourself 
// chat = sends to the current chat 
// off = Disables detection of deleted messages


global.statusemoji = process.env.STATUS_EMOJI || "🧡,💚,🔥,✨,❤️,🥰,😎";


global.autoviewstatus = process.env.AUTO_STATUS_VIEW || 'true'


global.autoreactstatus = process.env.AUTO_STATUS_REACT || 'false'


global.timezones = process.env.TIMEZONE || "Pakistan/Karachi" 

let file = require.resolve(__filename)
fs.watchFile(file, () => {
  fs.unwatchFile(file)
  console.log(`Updated '${__filename}'`)
  delete require.cache[file]
  require(file)
})
